version: 2
updates:
  - package-ecosystem: "github-actions"
    groups: # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
      github-actions:
        patterns:
        - "*"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gomod"
    groups:
      gomod-dependencies:
        patterns:
        - "*"
        exclude-patterns:
        # gardener/gardener dictates the k8s dependency
        - "k8s.io*"
        - "sigs.k8s.io/controller-runtime"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    ignore:
      # gardener/gardener dictates the k8s dependency
      - dependency-name: "k8s.io*"
      - dependency-name: "sigs.k8s.io/controller-runtime"
  - package-ecosystem: "docker"
    directory: "/hack" # should watch /hack/values-golang.yaml and create update PRs in case a new golang version is released
    schedule:
      interval: weekly
